name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # build whenever you push to main
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.harvgrotto }}
          password: ${{ secrets.dckr_pat_OKo8psA34HOcsyyxQEmkGbZCqfM }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.harvgrotto }}/comfyui:latest
